### ISSUE TITLE
add actual code to the sections to show how to program the math

### ISSUE THREAD

**Issue by Pomax** [Pomax/bezierinfo#17]
There's a lot of math in the article right now, but very few code snippets that show how to program the things that are described using mathematical functions. It'll be good to expose both sides of the story.

**Comment by tyoc213** [comment]
I think you could add references to suffused reading, I found for example http://stackoverflow.com/questions/2169641/where-to-find-algorithms-for-standard-math-functions which in turn have a link to http://people.math.sfu.ca/~cbm/aands/ which is http://www.nr.com/aands/

Also you could use links to https://en.wikipedia.org/wiki/List_of_algorithms#Numerical_algorithms it would be nice to find the required algos for example in python I guess???

**Comment by Pomax** [comment]
those links are too specific, really. The missing code note is mostly about the code used in the article itself, not generic algorithms. If you read a section on splitting a curve, or getting a derivative, seeing the code for that associated with the text that talks about it is more valuable than just having the text.

Even though of course you should still be able to follow along with high school math =)

**Comment by Pomax** [comment]
https://github.com/Pomax/BezierInfo-2/issues/233

**Comment by tyoc213** [comment]
I will read again all :)
