### ISSUE TITLE
add the "quick-and-dirty" way to compute arc length using flattening

### ISSUE THREAD

**Issue by Pomax** [Pomax/bezierinfo#56]
And give a sketch that shows the error that comes with that approach, compared to the true arc length.

**Comment by behdad** [comment]
yeah, I'm also interested in seeing error comparison of your integral approach with very small n...

**Comment by behdad** [comment]
Here's the lib2geom implementation:
http://bazaar.launchpad.net/~lib2geom-hackers/lib2geom/trunk/view/head:/src/2geom/bezier-curve.cpp#L283

**Comment by Pomax** [comment]
it's a hard thing to compare, though, since the curve's length (factoring in zoom) is relatively important too: a 0.2% error for a 300 pixel curve with 16 segments on a low dpi computer screen looks fine, but does not look fine on a 300dpi display, for instance.

Comparisons are over at http://pomax.github.io/bezierinfo/#arclengthapprox now

**Comment by behdad** [comment]
> it's a hard thing to compare, though, since the curve's length (factoring in zoom) is relatively important too: a 0.2% error for a 300 pixel curve with 16 segments on a low dpi computer screen looks fine, but does not look fine on a 300dpi display, for instance.

I don't agree.  Depends on what you use the curve length for of course.

> Comparisons are over at http://pomax.github.io/bezierinfo/#arclengthapprox now

Would it be possible for you to update the integral to allow changing number of segments using + / -?

**Comment by Pomax** [comment]
> I don't agree. Depends on what you use the curve length for of course.

quite.

> Would it be possible for you to update the integral to allow changing number of segments using + / -?

I can make that a thing in the section on true arc length. I though I already had, but maybe that was just a testing sketch I'd done before writing the section.
