### ISSUE TITLE
add +/- controls to the arc length sketch to pick the number of slices

### ISSUE THREAD

**Issue by Pomax** [Pomax/bezierinfo#57]
also add a quadratic example. It's silly to only show the cubic curve.

**Comment by Pomax** [comment]
The arc length section's cubic sketch has been updated with this information /cc @behdad

**Comment by behdad** [comment]
Looks good.  Thanks!  Can you add error percentage as well?  6 pieces looks quite good for many use cases.

**Comment by Pomax** [comment]
I can, although absolute values might be more meaningful.

**Comment by Pomax** [comment]
added.

**Comment by behdad** [comment]
Thanks.
